######################################################################
# Automatically generated by qmake (2.01a) Thu Jun 30 17:39:53 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . Data
INCLUDEPATH += . ..
QT+=opengl

# Input
HEADERS += Widget.h Wnd.h
SOURCES += main.cpp Widget.cpp Wnd.cpp
