######################################################################
# Automatically generated by qmake (1.06c) Sun Oct 3 19:37:41 2004
######################################################################

TEMPLATE = app

QT+=opengl

INCLUDEPATH += .
#LIBS += -lGLU

# Input
HEADERS += ../nehewidget.h ch10.h
SOURCES += main.cpp ../nehewidget.cpp

unix:!symbian {
    maemo5 {
        target.path = /opt/usr/bin
    } else {
        target.path = /usr/local/bin
    }
    INSTALLS += target
}
