######################################################################
# Automatically generated by qmake (1.06c) Sun Oct 3 19:37:41 2004
######################################################################

TEMPLATE = app

QT+=opengl

INCLUDEPATH += . ..
#LIBS += -lGLU

# Input
HEADERS += ../nehewidget.h ch10.h
SOURCES += main.cpp ../nehewidget.cpp


include(../config.pri)

#data+=world.txt
#data+=data

data.path=$$target.path/
data.files = *.txt

