Document: neheglqt
Title: Debian neheglqt Manual
Author: <insert document author here>
Abstract: This manual describes what neheglqt is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/neheglqt/neheglqt.sgml.gz

Format: postscript
Files: /usr/share/doc/neheglqt/neheglqt.ps.gz

Format: text
Files: /usr/share/doc/neheglqt/neheglqt.text.gz

Format: HTML
Index: /usr/share/doc/neheglqt/html/index.html
Files: /usr/share/doc/neheglqt/html/*.html
